name: Publish to PyPI

on:
  release:
    types: [published]


jobs:

  publish:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Creating Built Distributions
        run: python setup.py sdist

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}
          skip_existing: true
