name: Python package

on:
  push:
    branches:
      - master
      - '*.*.*'
  pull_request:
    branches:
      - master
      - '*.*.*'
  schedule:
    - cron:  '0 6 * * 1'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
        django-version: [
          '>=1.8,<1.9', '>=1.9,<1.10', '>=1.10,<1.11', '>=1.11,<1.12',
          '>=2.0,<2.1','>=2.1,<2.2', '>=2.2,<2.3',
          '>=3.0,<3.1'
        ]
        exclude:
          - python-version: 3.5
            django-version: '>=3.0,<3.1'

    name: Py${{ matrix.python-version }} | Django${{ matrix.django-version }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Tox and Django
        run: |
          pip install tox
          pip install "django${{ matrix.django-version }}"

      - name: Run Tox
        run: tox -e py

      - name: Upload coverage to Codecov
        if: matrix.python-version == 3.8
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    continue-on-error: true
    needs: test

    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Creating Built Distributions
        run: python setup.py bdist

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}
